### ISSUE TITLE
Improve variables naming 

### ISSUE THREAD

**Issue by tavaresrodrigo** [hugofco/Discount_Calculator#1]
Prefer more descriptive and concise variable names always following the pep8 recommendation, this way you make your code clear for other developers that may want to contribute to your code, ex: instead of p1 why not use price1? Try to apply it for all variables in your code.

PEP8:
[Function and Variable Names](https://peps.python.org/pep-0008/#function-and-variable-names)
Function names should be lowercase, with words separated by underscores as necessary to improve readability.

Variable names follow the same convention as function names.

mixedCase is allowed only in contexts where that’s already the prevailing style (e.g. threading.py), to retain backwards compatibility.

**Comment by hugofco** [comment]
I made the variables shorter for trying to make the 2.0 version of my program, and I forgot to rename them after I finished writing and testing the code.

**Comment by hugofco** [comment]
I made the variables shorter for trying to make the 2.0 version of my program, and I forgot to rename them after I finished writing and testing the code.

**Comment by tavaresrodrigo** [comment]
Well done @hugofco ! You rock!
