### ISSUE TITLE
Python functions

### ISSUE THREAD

**Issue by tavaresrodrigo** [hugofco/Discount_Calculator#2]
Functions are useful when you have  a block of code that is repeating in your program, if you wrap this code in a method/function, you will be able to call it with new parameters each time you want to execute the steps in the method. 

Try to identify in your code which parts could be better represented in a function. 

References:

https://www.w3schools.com/python/python_functions.asp
https://www.youtube.com/watch?v=NE97ylAnrz4

**Comment by hugofco** [comment]
I always wanted to use functions in my projects, but i never really found a opportunity to implement them, until now. I defined three functions, one for calculate the discount on the prices, another to ask the user the percentage he wants to discount from the product, and the third one calculates how much you have saved after the discount have been applied.

**Comment by tavaresrodrigo** [comment]
Well done @hugofco ! From now on you can use functions to make your code reusable and more structured.
